name: jrb_productions_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  pdf: 3.10.8
  signature: 5.4.1
  path_provider: 2.1.2
  share_plus: 7.2.2
  open_file_plus: 3.4.1
  geolocator: 11.0.0
  geocoding: 3.0.0
  shared_preferences: 2.2.2
  intl: 0.19.0
  permission_handler: 11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

